create table if not exists public.settings (
  profile_id text primary key,
  neon_intensity integer not null,
  sound_volume integer not null,
  motion_blur integer not null,
  reduced_motion boolean not null default false
);

create table if not exists public.lesson_progress (
  profile_id text not null,
  lesson_slug text not null,
  status text not null,
  attempts integer not null default 0,
  last_code_snapshot text not null default '',
  updated_at timestamptz not null default now(),
  primary key (profile_id, lesson_slug)
);

create table if not exists public.weekly_gate_results (
  profile_id text not null,
  week_start text not null,
  score integer not null,
  strengths_json jsonb not null default '[]'::jsonb,
  friction_points_json jsonb not null default '[]'::jsonb,
  completed_at timestamptz not null default now(),
  primary key (profile_id, week_start)
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  blueprint_slug text,
  title text not null,
  files_json jsonb not null default '{}'::jsonb,
  architecture_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.logic_posters (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  source_type text not null,
  source_ref text,
  title text not null,
  payload_json jsonb not null default '{}'::jsonb,
  visibility text not null default 'private',
  created_at timestamptz not null default now()
);

create table if not exists public.forge_challenges (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  target_realm text not null,
  title text not null,
  parameters_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  endpoint text not null,
  prompt_preview text not null,
  status text not null,
  latency_ms integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  event_type text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  title text not null,
  message text not null,
  kind text not null default 'info',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
